source "https://rubygems.org"
ruby "2.1.5"

gem "rails", "~> 4.2.0"

gem "activerecord-session_store"
gem "bitters"
gem "bourbon"
gem "cancancan"
gem "coffee-rails"
gem "devise"
gem "devise_invitable", "~> 1.3.4"
gem "dotenv-rails"
gem "draper"
gem "email_validator"
gem "faraday", "~> 0.8.6"
gem "font-awesome-sass", "~> 4.3.0"
gem "foreman"
gem "high_voltage"
gem "jquery-rails"
gem "kaminari"
gem "mandrill_mailer"
gem "neat"
gem "omniauth"
gem "omniauth-google-oauth2" 
gem "pg"
gem "redis"
gem "resque", branch: "1-x-stable", github: "resque/resque"
gem "resque-web", require: "resque_web"
gem "sass-rails"
gem "simple_form"
gem "stripe"
gem "uglifier"

group :development do 
  gem "better_errors"
end

group :development, :test do
  gem "binding_of_caller"
  gem "byebug"
  gem "pry-byebug"
  gem "capybara"
  gem "database_cleaner"
  gem "factory_girl_rails"
  gem "faker"
  gem "guard-rails"
  gem "guard-rspec"
  gem "rspec-rails", "~> 3.0"
  gem "shoulda-matchers"
  gem "spring"
  gem "stripe-ruby-mock", "~> 2.1.0", :require => "stripe_mock"
  gem "vcr"
end


